## Numpy array and basics

In [2]:
import numpy as numpy
import time

Creating Array from List

In [4]:
arr_1d = numpy.array([1, 2, 3, 4, 5])
print(arr_1d)

arr_2d = numpy.array([[1, 2, 3], [4, 5, 6]]) #numpy.array takes a single array
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


### List vs NumPy Array

In [ ]:
py_list = [1, 2, 3]
print("Python list multiplication ", py_list * 2)

np_array = numpy.array([1, 2, 3]) #element wise multiplication
print("Python array multiplication ", np_array * 2)

Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]


In [3]:
start = time.time()
py_list = [i*2 for i in range(10000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = numpy.arange(100000) * 2
print("\n Numpy operation time: ", time.time() - start)


 List operation time:  0.6882016658782959

 Numpy operation time:  0.028621912002563477


### Creating Array from Scratch

In [7]:
zeros = numpy.zeros((3, 4))
print("zeros array: \n", zeros)

ones = numpy.ones((2, 3))
print("Ones Array: \n", ones)

full = numpy.full((2, 2), 7)
print("Full Array: \n", full)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
Full Array: 
 [[7 7]
 [7 7]]


In [9]:
random = numpy.random.random((2, 3))
print("Random Array: \n", random) #Fluctuates between 0s & 1s

sequence = numpy.arange(0, 10, 2)
print("Sequence Array: \n", sequence)

Random Array: 
 [[0.65494126 0.85883624 0.72890387]
 [0.83441765 0.61956924 0.24398276]]
Sequence Array: 
 [0 2 4 6 8]


### Vector, Matrices, & Tensor

In [13]:
vector = numpy.array([1, 2, 3])
print("Vector: ", vector)

matrix = numpy.array([[1, 2, 3],
                      [4, 5, 6]])
print("Matrix: \n", matrix)

tensor = numpy.array([[[1, 2] , [3, 4]],
                      [[5, 6], [7, 8]]])
print("Tensor: \n", tensor)

Vector:  [1 2 3]
Matrix: 
 [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties 

In [14]:
arr = numpy.array([[1, 2, 3],
                   [4, 5, 6]])
print("Shape", arr.shape)
print("Dimension", arr.ndim)
print("Size", arr.size)
print("Data Type", arr.dtype)

Shape (2, 3)
Dimension 2
Size 6
Data Type int64


### Array Reshaping

In [23]:
arr = numpy.arange(12)
print("Orignal array: ", arr)

reshaped = arr.reshape((3, 4))
print("\n Reshaped array: \n", reshaped)

flattened = reshaped.flatten()
print("\n Flattened array: ", flattened)

# returns view, instead of copy
raveled = reshaped.ravel()
print("\n Raveled array: ", raveled)

# Transpose
transpose = reshaped.T
print("\n Transposed array: \n", transpose)


Orignal array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
