### NumPy Array Operations

In [1]:
import numpy as np

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic Slicing:" ,arr[2:7])

print("With Step:", arr[1:8:2])

print("Negative Indexing", arr[-3])

Basic Slicing: [3 4 5 6 7]
With Step: [2 4 6 8]
Negative Indexing 8


In [8]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Specific Element: ", arr_2d[1, 2])
print("Entire row", arr_2d[1])
print("Entire column", arr_2d[:, 1])

Specific Element:  6
Entire row [4 5 6]
Entire column [2 5 8]


### Sorting

In [11]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted Array: ", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print("Sorted 2D array by column: \n", np.sort(arr_2d_unsorted, axis=0))
print("Sorted 2D array by row: \n", np.sort(arr_2d_unsorted, axis=1))

Sorted Array:  [1 1 2 3 4 5 6 9]
Sorted 2D array by column: 
 [[1 1]
 [2 2]
 [3 3]]
Sorted 2D array by row: 
 [[1 3]
 [1 2]
 [2 3]]


### Filter

In [ ]:
numbers = np.arange(11)

even_number = numbers[numbers % 2 == 0]
print("Even: ", even_number)

Even:  [ 0  2  4  6  8 10]


### Filter with Mask

In [14]:
mask = numbers > 5
print("Numbers > 5: ", numbers[mask])

Numbers > 5:  [ 6  7  8  9 10]


### Fancy Indexing vs np.where()

In [16]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print("NP where", numbers[where_result])

[0 2 4]
NP where [ 6  7  8  9 10]


In [21]:
condition_array = np.where(numbers > 5, numbers * 4, numbers)
#condition_array = np.where(numbers > 5, "true" , "false")

print(condition_array)

[ 0  1  2  3  4  5 24 28 32 36 40]


### Addition & Removal of Data

In [22]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

#combined = arr1 + arr2 -> [5 7 9]
combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


### Array Compatibility

In [23]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

print("Compatibility shapes: ", a.shape == b.shape)

Compatibility shapes:  True


In [27]:
orignal = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((orignal, new_row)) #vstack -> adds new row
print(orignal)
print("New row: \n", with_new_row)

new_col = np.array([[7] , [8]])

with_new_col = np.hstack((orignal, new_col)) #hstack -> adds new column
print("New column: \n", with_new_col)

[[1 2]
 [3 4]]
New row: 
 [[1 2]
 [3 4]
 [5 6]]
New column: 
 [[1 2 7]
 [3 4 8]]


In [29]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2)

print("Array after deletion : ", deleted)

Array after deletion :  [1 2 4 5]
