### Vector Operations

In [1]:
import numpy as np

In [6]:
vector1 = np.array([1, 2, 3, 4, 5])
vector2 = np.array([6, 7, 8, 9, 10])

print(" Vector addition:", vector1 + vector2)
print("\n Vector Multiplication:", vector1 * vector2)
print("\n Dot Product:", np.dot(vector1, vector2))

angle = np.arccos(np.dot(vector1, vector2)/ (np.linalg.norm(vector1) * np.linalg.norm(vector2)))
print("\n Angle:",angle)

 Vector addition: [ 7  9 11 13 15]

 Vector Multiplication: [ 6 14 24 36 50]

 Dot Product: 130

 Angle: 0.26554161733900966


In [7]:
restaurant_types = np.array(['biryani', 'chinese', 'pizza', 'burger', 'cafe'])

vectorized_upper = np.vectorize(str.upper)
print("Vectorized Upper: ", vectorized_upper(restaurant_types))

Vectorized Upper:  ['BIRYANI' 'CHINESE' 'PIZZA' 'BURGER' 'CAFE']


### Broadcast

In [3]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]

sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],   # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],   # Beijing Bites
    [3, 200000, 230000, 260000, 300000],   # Pizza Hub
    [4, 180000, 210000, 240000, 270000],   # Burger Point
    [5, 160000, 185000, 205000, 230000]    # Chai Point
])

In [4]:
monthly_avg = sales_data[:, 1:] / 12

print(monthly_avg)

[[12500.         15000.         18333.33333333 20833.33333333]
 [10000.         11666.66666667 13333.33333333 15833.33333333]
 [16666.66666667 19166.66666667 21666.66666667 25000.        ]
 [15000.         17500.         20000.         22500.        ]
 [13333.33333333 15416.66666667 17083.33333333 19166.66666667]]
