## Numpy array and basics

In [6]:
import numpy as numpy
import time

Creating Array from List

In [4]:
arr_1d = numpy.array([1, 2, 3, 4, 5])
print(arr_1d)

arr_2d = numpy.array([[1, 2, 3], [4, 5, 6]]) #numpy.array takes a single array
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


### List vs NumPy Array

In [ ]:
py_list = [1, 2, 3]
print("Python list multiplication ", py_list * 2)

np_array = numpy.array([1, 2, 3]) #element wise multiplication
print("Python array multiplication ", np_array * 2)

Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]


In [ ]:
start = time.time()
py_list = [i*2 for i in range(10000000)]
print("\n List operation time: ", time.time() - start)